config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do 
    get 'latest', on: :collection
    get 'previous', on: :member
  end

  root 'posts#latest'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, presence: true

  scope :published, -> { where(published: true) }

  def has_previous_published?
    Post.published.where("created_at < :date", date: created_at).order(:created_at).any?
  end

  def self.latest_published
    self.published.order(:created_at).last
  end

  def self.previous_published(post)
    Post.published.where("created_at < :date", date: post.created_at).order(:created_at).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :previous]

  # GET /posts
  def index
    @posts = Post.all.order(created_at: :desc).page params[:page]
  end

  def latest
    @post = Post.latest_published
  end

  def previous
    @post = Post.previous_published(@post)

    if @post
      render :latest
    else
      redirect_to latest_posts_path, alert: t('.error')
    end
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to posts_url, notice: t('.notice') 
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to posts_url, notice: t('.notice')
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy

    redirect_to posts_url, notice: t('.notice')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :published)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/application/_menu.html.slim
nav.navbar.navbar-dark.bg-dark.navbar-expand-md
  a.navbar-brand href="#"  SG Blog
  button.navbar-toggler data-target="#navbarNav" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarNav.collapse.navbar-collapse.navbar-responsive-collapse
    ul.navbar-nav
      li.nav-item
        = link_to "Inicio", root_path, class: 'nav-link'
      li.nav-item
        = link_to "Admin", posts_path, class: 'nav-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    title SgBlog
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'menu'

    div.container
      == yield

app/views/posts/_flashes.html.slim
- if flash[:notice]
  div.alert.alert-success
    = flash[:notice]

- if flash[:alert]
  div.alert.alert-danger
    = flash[:alert]

app/views/posts/_form.html.slim
= simple_form_for(@post) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :body, input_html: {rows: 40}
    = f.input :published

  .form-actions
    = f.button :submit, class: 'btn btn-success'

app/views/posts/edit.html.slim
h1 = t '.title'

== render 'form'

= link_to t('.cancel'), posts_path

app/views/posts/index.html.slim
h1 = t('.title')
 
= render 'flashes'

table.table
  thead
    tr
      th = Post.human_attribute_name :title
      th = Post.human_attribute_name :created_at
      th = Post.human_attribute_name :published
      th

  tbody
    - @posts.each do |post|
      tr
        td = post.title
        td = l post.created_at.to_date
        td = t "boolean.#{post.published.to_s}"
        td 
          ul
            li = link_to t('.object_actions.show'), post
            li = link_to t('.object_actions.edit'), edit_post_path(post)
            li = link_to t('.object_actions.destroy'), post, data: { confirm: 'Are you sure?' }, method: :delete

= paginate @posts
br

= link_to t('.actions.new'), new_post_path, class: 'btn btn-primary'

app/views/posts/latest.html.slim
= render 'flashes'

- if @post
  h1 = @post.title

  p = @post.body

  = link_to  "<< #{t('.previous_post')}", previous_post_path(@post) if @post.has_previous_published?

- else 
  p = t '.no_publications'

app/views/posts/new.html.slim
h1 = t '.title'

== render 'form'

= link_to t('.cancel'), posts_path

app/views/posts/show.html.slim
h1 = @post.title

p = @post.body

=< link_to 'Back', posts_path